# Generated by Django 5.1.4 on 2024-12-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_score', models.IntegerField()),
                ('date_taken', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_score',
                'managed': False,
            },
        ),
    ]
