# Generated by Django 5.1.4 on 2024-12-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('answer', models.TextField()),
                ('type', models.CharField(choices=[('MC', 'Multiple Choice'), ('TF', 'True/False'), ('IDN', 'Identification')], default='MC', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
    ]
