# Generated by Django 5.1.4 on 2024-12-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('class_limit', models.IntegerField()),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
    ]
